services:
  erp-system:
    build: ./erp-system,
    volumes:
      - ./erp-system:/app

  ecommercesystem:
    build: ./ecommercesystem

  crm-system:
    build: ./crm-system

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"   
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  logservice:
    build: ./logservice
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - logging_network

networks:
  logging_network:
    driver: bridge